#!/bin/bash

echo "🔧 修复登录问题"
echo "================"
echo ""
echo "✅ 已修复 .env.local 中的 NEXTAUTH_URL"
echo "   从: http://localhost:8000"
echo "   到: http://localhost:3000"
echo ""
echo "⚠️  重要：需要重启开发服务器才能生效！"
echo ""
echo "请执行以下步骤："
echo ""
echo "1. 停止当前的开发服务器（按 Ctrl+C）"
echo "2. 重新启动服务器："
echo "   npm run dev"
echo ""
echo "3. 然后访问登录页面测试："
echo "   http://localhost:3000/login"
echo ""
echo "4. 如果还没有账号，先注册："
echo "   http://localhost:3000/register"
echo ""
echo "测试账号建议："
echo "   邮箱: test@example.com"
echo "   密码: testpassword123"
echo ""
echo "✅ 修复完成！"
